# tests/owner_state/test_firestore_contract.py
"""The engine half of the owner-state contract (#94).

tests/owner_state/test_pull.py feeds pull() documents written BY HAND — the engine's own idea
of what the browser sends. The browser never sent anything, and that test passed throughout.

This one reads tests/fixtures/owner_state_firestore_contract.json, which is GENERATED by
src/owner/__tests__/ownerStateContract.test.js from the real recordAnswer / recordOutcome.
The two tests share one file and neither may edit it by hand, so a change to either side's
shape or schema breaks one of them rather than neither.
"""
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from src.owner_state.model import SCHEMA, answered_cost, standing_outcome
from src.owner_state.pull import pull

FIXTURE = ROOT / "tests" / "fixtures" / "owner_state_firestore_contract.json"
STORE = "yomyom-kafr-qasim"
FIXED = 1789290000000                 # the browser test's clock, 2026-09-13T09:00:00Z
DAY = 24 * 60 * 60 * 1000


class _Doc:
    def __init__(self, id, data): self.id, self._data = id, data
    def to_dict(self): return self._data


class _Client:
    """Serves the fixture the way firestore.Client streams stores/{store}/ownerState."""
    def __init__(self, docs): self._docs = docs
    def collection(self, path):
        assert path == f"stores/{STORE}/ownerState", path
        docs = self._docs
        return type("Col", (), {"stream": lambda self: iter(_Doc(k, v) for k, v in docs.items())})()


def _pulled():
    docs = json.loads(FIXTURE.read_text(encoding="utf-8"))
    return pull(project_id="p", store_id=STORE, credentials_json=None, credentials_path=None, client=_Client(docs))


def test_the_browser_schema_is_the_one_the_engine_accepts():
    """The browser's local state carried schema 2. pull() rejects anything but SCHEMA as
    `owner_state_schema`, so had the write-through sent 2 the engine would have gone from
    reading nothing to refusing everything."""
    docs = json.loads(FIXTURE.read_text(encoding="utf-8"))
    assert docs["meta"]["schema"] == SCHEMA
    state = _pulled()
    assert state.status == "available", state.reason


def test_a_browser_cost_answer_reaches_answered_cost():
    """§9.4: the owner's answer must be readable where the engine looks for it."""
    state = _pulled()
    assert answered_cost(state, "7290000041445") == 9.9


def test_a_barcode_with_leading_zeros_is_found_in_either_form():
    """Keying on the wrong form of a barcode is one of rule 12's four silent failures. The
    browser writes '00729012345'; the engine normalises; both spellings must find it."""
    state = _pulled()
    assert answered_cost(state, "00729012345") == 4.5
    assert answered_cost(state, "729012345") == 4.5


def test_browser_outcomes_are_standing_outcomes_to_the_engine():
    state = _pulled()
    now = FIXED + DAY
    assert standing_outcome(state, "a1b2c3d4e5f60718", now)["status"] == "acted"
    assert standing_outcome(state, "0f1e2d3c4b5a6978", now)["status"] == "declined"
    assert standing_outcome(state, "8f6ebc2c4a19e4f4", now)["status"] == "deferred"


def test_a_deferral_lapses_when_the_browser_said_it_would():
    state = _pulled()
    assert standing_outcome(state, "8f6ebc2c4a19e4f4", FIXED + 8 * DAY) is None


def test_the_snapshot_carries_the_signal_family_to_the_engine():
    """ADR-016: the family is the only durable grouping key INT-MEAS has."""
    state = _pulled()
    assert state.outcomes["a1b2c3d4e5f60718"]["snapshot"]["signal_family"] == "price.inverted"
