import { describe, expect, it } from 'vitest'

import { normalizeProduct, normalizeProducts } from '../productAdapter.js'

function rawProduct(overrides = {}) {
  return {
    id: 'ym-7290000066318',
    name: 'קוקה קולה 1.5 ליטר',
    category: 'משקאות',
    currentStock: 12,
    price: 8.9,
    cost: 5.5,
    supplier: 'Tempo',
    leadTimeDays: 7,
    ...overrides,
  }
}

// normalizeProduct builds a fixed-shape object literal: a field that is not
// named in it is discarded, whatever the pipeline wrote. That is how
// leadTimeSource and leadTimeConfidence came to be generated by
// normalize-datasets.mjs and read by nobody, while two documents claimed the
// app said honestly when a lead time was assumed.
describe('lead-time provenance survives normalization', () => {
  it('carries a measured lead time through with its confidence', () => {
    const { product } = normalizeProduct(
      rawProduct({ leadTimeSource: 'measured', leadTimeConfidence: 'high' }),
    )
    expect(product.leadTimeDays).toBe(7)
    expect(product.leadTimeSource).toBe('measured')
    expect(product.leadTimeConfidence).toBe('high')
  })

  it('carries the default marker through', () => {
    const { product } = normalizeProduct(
      rawProduct({ leadTimeSource: 'default', leadTimeConfidence: 'low' }),
    )
    expect(product.leadTimeSource).toBe('default')
    expect(product.leadTimeConfidence).toBe('low')
  })

  it('treats a product with no provenance at all as assumed', () => {
    // A CSV upload or the demo connector carries no ledger metadata. It never
    // had a delivery interval observed, so 'default' is the honest reading.
    const { product } = normalizeProduct(rawProduct())
    expect(product.leadTimeSource).toBe('default')
    expect(product.leadTimeConfidence).toBe('low')
  })

  it('refuses to promote junk to measured, or to invent a confidence level', () => {
    const { product } = normalizeProduct(
      rawProduct({ leadTimeSource: 'MEASURED?', leadTimeConfidence: 'very sure' }),
    )
    expect(product.leadTimeSource).toBe('default')
    expect(product.leadTimeConfidence).toBe('low')
  })

  it('applies the same rule across a whole batch', () => {
    const { products } = normalizeProducts([
      rawProduct({ id: 'a', leadTimeSource: 'measured', leadTimeConfidence: 'medium' }),
      rawProduct({ id: 'b' }),
    ])
    expect(products.map((p) => p.leadTimeSource)).toEqual(['measured', 'default'])
    expect(products.map((p) => p.leadTimeConfidence)).toEqual(['medium', 'low'])
  })
})
