"""
export_store_types.py — publish configs/store_types.yaml to the frontend.

The browser cannot read YAML, and the store-format filter has to run in the same
place the recommendations are built. This writes the config out as a plain data
module so `src/lib/analytics/storeFormat.js` can enforce it with no parsing and no
network call.

Reads:  configs/store_types.yaml (+ configs/store_types.inferred.yaml if present)
Writes: src/data/storeTypes.js

Run this after editing either YAML file:
    python3 scripts/export_store_types.py
"""

from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.common.store_types import load_store_types

OUTPUT = ROOT / "src" / "data" / "storeTypes.js"

# The anchor every affinity lookup starts from. Matches OUR_STORE.storeId in
# scripts/export_competitor_market_data.py.
OUR_STORE_ID = "yomyom-kq-01"


def main() -> int:
    config = load_store_types()

    formats = {
        name: {
            "labelEn": meta.get("label_en"),
            "labelHe": meta.get("label_he"),
            "labelAr": meta.get("label_ar"),
            "typicalSkuRange": meta.get("typical_sku_range"),
        }
        for name, meta in config.formats.items()
    }

    stores = {
        store_id: {
            "storeType": record.store_type,
            "verified": record.verified,
            "basis": record.basis,
            "name": record.name,
            **({"chain": record.chain} if record.chain else {}),
            **({"distinctSkus": record.distinct_skus} if record.distinct_skus else {}),
        }
        for store_id, record in sorted(config.stores.items())
    }

    our_type = config.store_type(OUR_STORE_ID)
    excluded = config.excluded_stores(our_type)

    def dump(value) -> str:
        return json.dumps(value, ensure_ascii=False, indent=2)

    content = f"""// AUTO-GENERATED by scripts/export_store_types.py — do not edit.
// Generated: {datetime.now(timezone.utc).isoformat()}
// Source: configs/store_types.yaml
//
// Store identity. Without it the engines treat a hypermarket and a forecourt shop
// as equivalent price sources and recommend 24-packs to a gas station.
// Enforcement lives in src/lib/analytics/storeFormat.js.

export const OUR_STORE_ID = {json.dumps(OUR_STORE_ID)}

/** Our own format — the anchor of every affinity lookup. */
export const OUR_STORE_TYPE = {json.dumps(our_type)}

export const STORE_FORMATS = {dump(formats)}

/** affinity[ourFormat][theirFormat] → 0.0 (never compare) … 1.0 (same format) */
export const STORE_AFFINITY = {dump(config.affinity_matrix)}

/** Minimum affinity for a source to DRIVE a recommendation. Below it: context only. */
export const MIN_AFFINITY = {json.dumps(config.min_affinity)}

/** `manual` is human-verified. `proposed` and `inferred` are guesses — label them. */
export const STORE_TYPES = {dump(stores)}

/** Branches at affinity 0.0 from our format. These must never reach an engine. */
export const NEVER_COMPARE_STORE_IDS = {dump(excluded)}
"""

    OUTPUT.write_text(content, encoding="utf-8")

    verified = sum(1 for r in config.stores.values() if r.is_verified)
    first_hand = sum(1 for r in config.stores.values() if r.is_first_hand)
    print(f"Wrote {OUTPUT}")
    print(f"  our store: {OUR_STORE_ID} ({our_type})")
    print(f"  {len(stores)} branches — {verified} decided, {len(stores) - verified} unverified")
    print(f"  of the decided: {first_hand} first-hand, {verified - first_hand} from chain format")
    print(f"  min_affinity={config.min_affinity}, never-compare: {len(excluded)}")
    for store_id in excluded:
        record = config.store(store_id)
        print(f"    - {store_id} ({record.store_type}) {record.name or ''}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
