"""
Export competitor price data to src/data/marketData.js.
Reads: data/matching/barcode_matches.parquet
       data/external/silver/products/delivery_catalog/
Writes: src/data/marketData.js
"""
import polars as pl
import json
from pathlib import Path
from datetime import datetime

MATCHES = Path("data/matching/barcode_matches.parquet")
DELIVERY_SILVER = Path("data/external/silver/products/delivery_catalog")
OUTPUT = Path("src/data/marketData.js")

CHAIN_META = {
    "kaggle_dor_alon": {
        "brand": "Dor Alon",
        "storeName": "Alonit Kafr Qasim",
        "storeId": "dor-alon-kq-01",
        "coords": {"lat": 32.114, "lon": 34.978},
        "distance_m": 1400,
    },
    "kaggle_rami_levy": {
        "brand": "Rami Levy",
        "storeName": "Rami Levy Petah Tikva",
        "storeId": "rami-levy-pt-01",
        "coords": {"lat": 32.089, "lon": 34.887},
        "distance_m": 2100,
    },
    "kaggle_shufersal": {
        "brand": "Shufersal",
        "storeName": "Shufersal Deal Petah Tikva",
        "storeId": "shufersal-pt-01",
        "coords": {"lat": 32.093, "lon": 34.890},
        "distance_m": 1800,
    },
}

OUR_STORE = {
    "brand": "YomYom",
    "storeName": "YomYom Kafr Qasim",
    "storeId": "yomyom-kq-01",
    "coords": {"lat": 32.114, "lon": 34.972},
}


def load_wolt_availability() -> set:
    available = set()
    parquet_files = list(DELIVERY_SILVER.rglob("*.parquet"))
    if not parquet_files:
        return available
    # Skip malformed files — failed scrapes produce single-column _empty files
    valid = [pl.read_parquet(f) for f in parquet_files if len(pl.read_parquet(f).columns) > 1]
    if not valid:
        return available
    df = pl.concat(valid)
    if "barcode" in df.columns and "is_online_available" in df.columns:
        online = df.filter(
            pl.col("is_online_available") == True,
            pl.col("barcode").is_not_null(),
        )
        available = set(online["barcode"].cast(pl.Utf8).to_list())
    return available


def main():
    if not MATCHES.exists():
        print("ERROR: data/matching/barcode_matches.parquet not found. Run join_yomyom_kaggle.py first.")
        return

    matches = pl.read_parquet(MATCHES)
    wolt_available = load_wolt_availability()

    competitor_stores = []
    barcode_to_product_id = {}
    product_id_to_barcode = {}

    for chain, meta in CHAIN_META.items():
        chain_rows = matches.filter(pl.col("chain") == chain)
        if len(chain_rows) == 0:
            continue

        snapshot = {}
        for row in chain_rows.iter_rows(named=True):
            barcode = str(row["barcode"])
            price = row["kaggle_price"]
            if price is None or price <= 0:
                continue
            snapshot[barcode] = {
                "price": round(float(price), 2),
                "isAvailable": barcode in wolt_available,
            }
            if barcode not in barcode_to_product_id:
                product_id = f"ym-{barcode}"
                barcode_to_product_id[barcode] = product_id
                product_id_to_barcode[product_id] = barcode

        competitor_stores.append({**meta, "snapshot": snapshot})

    js_content = f"""// AUTO-GENERATED by scripts/export_competitor_market_data.py
// Generated: {datetime.utcnow().isoformat()}Z
// Source: data/matching/barcode_matches.parquet

export const OUR_STORE = {json.dumps(OUR_STORE, ensure_ascii=False, indent=2)}

export const COMPETITOR_STORES = {json.dumps(competitor_stores, ensure_ascii=False, indent=2)}

export const BARCODE_TO_PRODUCT_ID = {json.dumps(barcode_to_product_id, ensure_ascii=False, indent=2)}

export const PRODUCT_ID_TO_BARCODE = {json.dumps(product_id_to_barcode, ensure_ascii=False, indent=2)}
"""

    OUTPUT.write_text(js_content, encoding="utf-8")
    total_barcodes = sum(len(s["snapshot"]) for s in competitor_stores)
    print(f"Wrote {OUTPUT}: {len(competitor_stores)} stores, {total_barcodes} barcode entries")


if __name__ == "__main__":
    main()
