import { formatCurrency } from '../../components/shared/formatters.js'

export function buildOptimizationReport({
  analyzedProducts,
  competitorSummary,
  dashboardStats,
  inventorySummary,
  marketContext,
  planogramItems,
  planogramSummary,
  recommendations,
  affinitySuggestions,
}) {
  const timestamp = new Date().toLocaleString()
  const sections = []

  sections.push(`# SmartShelf AI — Shelf Optimization Report`)
  sections.push(`**Generated:** ${timestamp}  `)
  sections.push(`**Store:** Demo Convenience Store  `)
  sections.push(`**Analysis Engine:** SmartShelf AI v2.0\n`)

  sections.push(`---\n`)
  sections.push(`## Executive Summary\n`)
  sections.push(buildExecutiveSummary(dashboardStats, inventorySummary, planogramSummary))

  sections.push(`## Inventory Health Overview\n`)
  sections.push(buildInventorySection(inventorySummary, analyzedProducts))

  sections.push(`## Planogram Analysis\n`)
  sections.push(buildPlanogramSection(planogramItems, planogramSummary))

  if (competitorSummary) {
    sections.push(`## Competitor Intelligence\n`)
    sections.push(buildCompetitorSection(competitorSummary))
  }

  sections.push(`## Reorder Priorities\n`)
  sections.push(buildReorderSection(recommendations))

  if (affinitySuggestions?.length > 0) {
    sections.push(`## Cross-Merchandising Opportunities\n`)
    sections.push(buildAffinitySection(affinitySuggestions))
  }

  if (marketContext) {
    sections.push(`## Market Context Signals\n`)
    sections.push(buildMarketContextSection(marketContext))
  }

  sections.push(`## Recommended Action Plan\n`)
  sections.push(buildActionPlan(planogramItems, recommendations, competitorSummary))

  sections.push(`---\n`)
  sections.push(`*This report was generated by SmartShelf AI using deterministic retail analytics, competitor intelligence, and cross-merchandising algorithms. For the most accurate results, ensure your product catalog and sales data are up to date.*`)

  return sections.join('\n')
}

function buildExecutiveSummary(stats, inventory, planogram) {
  const lines = []
  lines.push(`The store currently tracks **${inventory?.totalProducts ?? 0} products** across all categories.\n`)
  lines.push(`| Metric | Value |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Total SKUs | ${inventory?.totalProducts ?? 0} |`)
  lines.push(`| High Risk Stockouts | ${stats?.highRiskStockouts ?? 0} |`)
  lines.push(`| Reorder Suggestions | ${stats?.reorderSuggestions ?? 0} |`)
  lines.push(`| Estimated Order Cost | ${formatCurrency(stats?.estimatedOrderCost ?? 0)} |`)
  lines.push(`| Planogram Items | ${planogram?.totalItems ?? 0} |`)
  lines.push(`| Eye-Level Placements | ${planogram?.eyeLevelItems ?? 0} |`)
  lines.push(`| Total Facings | ${planogram?.totalFacings ?? 0} |`)
  lines.push(``)
  return lines.join('\n')
}

function buildInventorySection(inventory, products) {
  const lines = []

  const statusCounts = {}
  for (const p of products) {
    for (const s of p.analytics?.statuses ?? []) {
      statusCounts[s] = (statusCounts[s] ?? 0) + 1
    }
  }

  lines.push(`| Status | Count |`)
  lines.push(`|--------|-------|`)
  for (const [status, count] of Object.entries(statusCounts).sort((a, b) => b[1] - a[1])) {
    lines.push(`| ${status} | ${count} |`)
  }
  lines.push(``)

  const topVelocity = [...products]
    .sort((a, b) => (b.analytics?.weightedAvgDailySales ?? 0) - (a.analytics?.weightedAvgDailySales ?? 0))
    .slice(0, 5)

  if (topVelocity.length > 0) {
    lines.push(`### Top 5 by Sales Velocity\n`)
    lines.push(`| Product | Category | Units/Day |`)
    lines.push(`|---------|----------|-----------|`)
    for (const p of topVelocity) {
      lines.push(`| ${p.name} | ${p.category} | ${p.analytics.weightedAvgDailySales} |`)
    }
    lines.push(``)
  }

  return lines.join('\n')
}

function buildPlanogramSection(items, summary) {
  const lines = []
  lines.push(`The planogram engine placed **${summary.totalItems} products** with a total of **${summary.totalFacings} facings**. **${summary.eyeLevelItems} products** earned premium eye-level placement.\n`)

  const byShelf = { EYE_LEVEL: [], MIDDLE: [], TOP: [], BOTTOM: [] }
  for (const item of items) {
    byShelf[item.shelfLevel]?.push(item)
  }

  const shelfLabels = { EYE_LEVEL: 'Eye Level', MIDDLE: 'Middle', TOP: 'Top', BOTTOM: 'Bottom' }
  lines.push(`| Shelf Level | Products | Avg Score |`)
  lines.push(`|-------------|----------|-----------|`)
  for (const [level, label] of Object.entries(shelfLabels)) {
    const group = byShelf[level] ?? []
    const avg = group.length > 0
      ? (group.reduce((s, i) => s + i.score, 0) / group.length).toFixed(1)
      : '—'
    lines.push(`| ${label} | ${group.length} | ${avg} |`)
  }
  lines.push(``)

  const topScorers = [...items].sort((a, b) => b.score - a.score).slice(0, 5)
  if (topScorers.length > 0) {
    lines.push(`### Top 5 Products by Planogram Score\n`)
    lines.push(`| Product | Shelf | Score | Facings | Reason |`)
    lines.push(`|---------|-------|-------|---------|--------|`)
    for (const item of topScorers) {
      lines.push(`| ${item.productName} | ${item.shelfLabel} | ${item.score.toFixed(1)} | ${item.facings} | ${item.reason} |`)
    }
    lines.push(``)
  }

  return lines.join('\n')
}

function buildCompetitorSection(summary) {
  const lines = []
  lines.push(`| Signal | Count |`)
  lines.push(`|--------|-------|`)
  lines.push(`| Local Price Leaders | ${summary.priceLeaderCount ?? 0} |`)
  lines.push(`| Competitor OOS Opportunities | ${summary.competitorOOSCount ?? 0} |`)
  lines.push(`| Price Protection Alerts | ${summary.priceProtectionCount ?? 0} |`)
  lines.push(`| Tracked SKUs | ${summary.productsWithCoverage ?? 0} |`)
  lines.push(``)
  lines.push(`**Key Insight:** ${summary.priceLeaderCount > 0 ? `We are the price leader on ${summary.priceLeaderCount} items — these should get premium shelf placement to maximize conversion.` : 'No price leadership detected — consider running competitive pricing analysis.'}`)
  lines.push(``)
  if (summary.competitorOOSCount > 0) {
    lines.push(`**Opportunity:** ${summary.competitorOOSCount} competitor stockout(s) detected within 1km — increase facings and consider temporary promotions to capture displaced demand.`)
    lines.push(``)
  }
  return lines.join('\n')
}

function buildReorderSection(recommendations) {
  const reorders = recommendations.filter((r) => r.type === 'REORDER')
  const byUrgency = { HIGH: [], MEDIUM: [], LOW: [] }
  for (const r of reorders) {
    const bucket = byUrgency[r.urgency] ?? byUrgency.LOW
    bucket.push(r)
  }

  const lines = []
  lines.push(`Total reorder suggestions: **${reorders.length}**\n`)

  for (const [urgency, items] of Object.entries(byUrgency)) {
    if (items.length === 0) continue
    lines.push(`### ${urgency} Urgency (${items.length} items)\n`)
    lines.push(`| Product | Qty | Reason |`)
    lines.push(`|---------|-----|--------|`)
    for (const r of items.slice(0, 8)) {
      lines.push(`| ${r.productName} | ${r.recommendedOrderQuantity} | ${r.reason} |`)
    }
    if (items.length > 8) lines.push(`| ... and ${items.length - 8} more | | |`)
    lines.push(``)
  }

  return lines.join('\n')
}

function buildAffinitySection(suggestions) {
  const lines = []
  const highImpact = suggestions.filter((s) => s.priority === 'HIGH')
  lines.push(`Identified **${suggestions.length} cross-merchandising pairs** (${highImpact.length} high-impact).\n`)

  lines.push(`| Anchor | Pair With | Strength | Est. Lift | Action |`)
  lines.push(`|--------|-----------|----------|-----------|--------|`)
  for (const s of suggestions.slice(0, 8)) {
    lines.push(`| ${s.anchor.name} | ${s.partner.name} | ${Math.round(s.strength * 100)}% | +${Math.round(s.liftEstimate * 100)}% | ${s.placement} |`)
  }
  lines.push(``)
  return lines.join('\n')
}

function buildMarketContextSection(ctx) {
  const lines = []
  if (ctx.weather) {
    lines.push(`- **Weather:** ${ctx.weather.summary ?? 'Normal conditions'}`)
  }
  if (ctx.holidays?.length > 0) {
    lines.push(`- **Upcoming Holidays:** ${ctx.holidays.map((h) => h.name).join(', ')}`)
  }
  if (ctx.news?.length > 0) {
    lines.push(`- **Market News:** ${ctx.news.slice(0, 3).map((n) => n.headline ?? n.title ?? n).join('; ')}`)
  }
  if (lines.length === 0) {
    lines.push(`No external market signals are currently active.`)
  }
  lines.push(``)
  return lines.join('\n')
}

function buildActionPlan(planogramItems, recommendations, competitorSummary) {
  const lines = []
  const actions = []

  const highUrgency = recommendations.filter((r) => r.urgency === 'HIGH' && r.type === 'REORDER')
  if (highUrgency.length > 0) {
    actions.push(`1. **Immediate Reorder:** Place orders for ${highUrgency.length} critical items to prevent stockouts. Estimated impact: preserves revenue on high-velocity SKUs.`)
  }

  const eyeLevel = planogramItems.filter((i) => i.shelfLevel === 'EYE_LEVEL')
  if (eyeLevel.length > 0) {
    actions.push(`${actions.length + 1}. **Eye-Level Optimization:** Verify that the top ${Math.min(eyeLevel.length, 5)} scored products are placed at eye level. These products drive the highest margin per facing.`)
  }

  if (competitorSummary?.competitorOOSCount > 0) {
    actions.push(`${actions.length + 1}. **Capture Competitor Demand:** Increase facings for ${competitorSummary.competitorOOSCount} items where nearby competitors are out of stock. Time-sensitive opportunity.`)
  }

  if (competitorSummary?.priceProtectionCount > 0) {
    actions.push(`${actions.length + 1}. **Price Review:** Evaluate pricing on ${competitorSummary.priceProtectionCount} items where competitors undercut by >15%. Consider promotional pricing or bundle offers.`)
  }

  const promos = recommendations.filter((r) => r.type === 'PROMOTION')
  if (promos.length > 0) {
    actions.push(`${actions.length + 1}. **Run Promotions:** ${promos.length} products flagged for promotional clearance to reduce waste and free shelf space.`)
  }

  actions.push(`${actions.length + 1}. **Schedule Next Audit:** Re-run shelf analysis in 7 days to track compliance and measure improvement.`)

  lines.push(actions.join('\n\n'))
  lines.push(``)
  return lines.join('\n')
}
