import { readFileSync, writeFileSync } from 'node:fs'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { resetPushForTests, setRemoteLoaderForTests } from '../remoteOwnerState'
import { ANSWER_STATUS, OUTCOME_STATUS, recordAnswer, recordOutcome, resetCacheForTests } from '../ownerState'
import { createFakeFirestore } from './fakeFirestore'

/**
 * THE CROSS-LANGUAGE CONTRACT (#94)
 *
 * Owner state was lost at exactly one seam: what the browser writes versus what
 * src/owner_state/pull.py reads. Each side was tested against itself — ownerState.test.js
 * against localStorage, test_pull.py against documents it wrote BY HAND — so the seam was
 * never crossed and nothing noticed that the browser wrote nothing at all.
 *
 * This test drives the real recordAnswer/recordOutcome and captures the Firestore documents
 * they produce. They must equal tests/fixtures/owner_state_firestore_contract.json, which
 * tests/owner_state/test_firestore_contract.py feeds to the real pull(). Change the browser's
 * shape or schema and this fails; change what the engine accepts and that one fails. The file
 * in the middle is generated by this test, never written by hand:
 *
 *     UPDATE_CONTRACT_FIXTURE=1 npx vitest run src/owner/__tests__/ownerStateContract.test.js
 */
const FIXTURE = new URL('../../../tests/fixtures/owner_state_firestore_contract.json', import.meta.url)
const FIXED = Date.UTC(2026, 8, 13, 9, 0, 0)          // 2026-09-13T09:00:00Z
const DAY = 24 * 60 * 60 * 1000
const settle = () => new Promise((r) => setTimeout(r, 0))

function createStorage() {
  const m = new Map()
  return { getItem: (k) => (m.has(k) ? m.get(k) : null), setItem: (k, v) => m.set(k, v), removeItem: (k) => m.delete(k), clear: () => m.clear() }
}

beforeEach(() => {
  globalThis.localStorage = createStorage()
  resetCacheForTests()
  resetPushForTests()
  vi.useFakeTimers({ toFake: ['Date'] })   // Date only: settle() still needs a real setTimeout
  vi.setSystemTime(FIXED)
})
afterEach(() => { vi.useRealTimers() })

async function produceDocuments() {
  const fake = createFakeFirestore()
  setRemoteLoaderForTests(fake.loader)

  // a valued confirmed loss the owner acted on
  await recordOutcome({ id: 'a1b2c3d4e5f60718', signal_family: 'price.inverted', capability: 'price_consistency',
    barcode: '7290000041445', characterisation: 'confirmed_loss',
    value: { amount: 16, kind: 'per_sale', certainty: 'confirmed' } }, { status: OUTCOME_STATUS.ACTED })
  // a hygiene record he declined, with a reason and no value
  await recordOutcome({ id: '0f1e2d3c4b5a6978', signal_family: 'hygiene.negative_stock', capability: 'hygiene',
    barcode: '7290019153696', characterisation: 'hygiene' }, { status: OUTCOME_STATUS.DECLINED, reason: 'not_worth_it' })
  // a competitor breach he deferred for a week
  await recordOutcome({ id: '8f6ebc2c4a19e4f4', signal_family: 'competitor.policy_breach', capability: 'competitor_position',
    barcode: '7290017888729', characterisation: 'policy_breach_review' },
  { status: OUTCOME_STATUS.DEFERRED, deferredUntil: FIXED + 7 * DAY })
  // a cost answer, and one on a barcode with leading zeros — keying on the wrong form of a
  // barcode is one of the four silent failures CLAUDE.md rule 12 records
  await recordAnswer('7290000041445', { value: 9.9, status: ANSWER_STATUS.ANSWERED })
  await recordAnswer('00729012345', { value: 4.5, status: ANSWER_STATUS.ANSWERED })

  await settle()
  return fake.ownerStateDocs()
}

describe('owner state crosses the browser → Firestore → engine seam intact', () => {
  it('produces exactly the documents the engine contract fixture holds', async () => {
    const docs = await produceDocuments()
    if (process.env.UPDATE_CONTRACT_FIXTURE === '1') {
      writeFileSync(FIXTURE, JSON.stringify(docs, null, 2) + '\n')
    }
    expect(docs).toEqual(JSON.parse(readFileSync(FIXTURE, 'utf8')))
  })

  it('writes the four documents pull.py streams, and meta.schema is the one it accepts', async () => {
    const docs = await produceDocuments()
    expect(Object.keys(docs).sort()).toEqual(['answers', 'meta', 'outcomes'])   // revivals: nothing recorded
    expect(docs.meta.schema).toBe(1)
  })
})
