/**
 * The shelf-build sheet — the only output of this module that gets executed.
 *
 * Everything else SmartShelf produces for the planogram is a picture on a
 * screen. This is the list a shop worker carries to the aisle: which product,
 * which shelf, how far along, how many facings, how many units to bring from the
 * back room.
 *
 * THREE DECISIONS THAT MAKE IT USABLE RATHER THAN IMPRESSIVE
 *
 *   1. Ordered by the work, not by the score. Shelf by shelf, left to right.
 *      Nobody builds a shelf in descending profit order.
 *
 *   2. Units are capped at what is actually in stock. The plan may want 12 units
 *      of a product with 5 in the back room; printing "12" sends someone on a
 *      wasted trip and costs the sheet its credibility. It prints 5 and states
 *      the shortfall of 7 — which is a reorder signal, not a failure.
 *
 *   3. A running centimetre offset. "Third position on shelf 2" is ambiguous
 *      once someone has already deviated; "starts at 47cm" is not.
 */

/** One row per position, in the order the shelf is physically built. */
export function buildSheetRows(plan) {
  const rows = []

  for (const shelf of plan?.shelves ?? []) {
    let startCm = 0
    let position = 0

    for (const item of shelf.items ?? []) {
      position += 1
      const stock = Math.max(0, item.currentStock ?? 0)
      const wanted = item.onShelf ?? 0

      rows.push({
        shelfCode: shelf.code,
        shelfLevel: shelf.shelfLevel,
        levelLabel: shelf.levelLabel,
        position,
        startCm: round(startCm),
        productId: item.productId,
        productName: item.productName,
        facings: item.facings,
        depthUnits: item.depthUnits,
        stack: item.stack,
        widthCm: item.widthCm,
        // What to actually carry to the shelf.
        unitsToPlace: Math.min(wanted, stock),
        shortfall: Math.max(0, wanted - stock),
        unfillable: stock <= 0,
        status: item.status,
      })

      startCm += item.facings * item.widthCm
    }
  }

  return rows
}

const COLUMNS = [
  ['shelf', (row) => row.shelfCode],
  ['level', (row) => row.levelLabel ?? row.shelfLevel ?? ''],
  ['position', (row) => row.position],
  ['start_cm', (row) => row.startCm],
  ['product_id', (row) => quote(row.productId)],
  ['product_name', (row) => quote(row.productName)],
  ['facings', (row) => row.facings],
  ['depth_units', (row) => row.depthUnits],
  ['units_to_place', (row) => row.unitsToPlace],
  ['shortfall', (row) => row.shortfall],
]

/**
 * CSV for printing or for handing to whatever the store already uses.
 *
 * Only `product_id` and `product_name` are quoted, because only those two come
 * from the POS and can therefore contain a comma. Shelf codes and level labels
 * are generated by this codebase from a fixed vocabulary. Quoting only the
 * untrusted fields keeps the file readable in a text editor, which matters when
 * the person opening it is a shop manager rather than a spreadsheet.
 */
export function toBuildSheetCsv(plan) {
  const header = COLUMNS.map(([name]) => name).join(',')
  const lines = buildSheetRows(plan).map((row) =>
    COLUMNS.map(([, read]) => read(row)).join(','),
  )
  return [header, ...lines].join('\n')
}

function quote(value) {
  return `"${String(value ?? '').replace(/"/g, '""')}"`
}

function round(value) {
  return Math.round(value * 100) / 100
}
